noir-lang/vscode-noir

src/extension.ts

Resolves 
While diving into various fixes for the `Run test` code lens, I found that we didn't accept multiple arguments to the registered command. This change allows it to accept more than one argument.

fix: Accept multiple arguments for a registered command

---

src/extension.ts

Ref https://github.com/noir-lang/noir/pull/2330 
This adds a `nargo.execute` command that will be triggered via the `> Execute` code lens.

feat: Add execute command to handle Execute code lens

---

src/client.ts
src/constants.ts
src/extension.ts
src/find-nargo.ts

Resolves 
This refactors the client construction and startup so it can be shared between workspaces and files. It also becomes its own class that extends the LanguageClient so we can attach other items, such as the Test Controller in #33, that are disposed with the client.

chore: Separate Client into own class

---

syntaxes/noir.tmLanguage.json

Resolves 
This PR updates the grammar to handle various new language features which we've added. It's not perfect (The `&` in `&mut` doesn't get highlighted for some reason) but it's a big improvement over the current.
Changes:
- hex numbers now get consistently marked as a numeric literal rather than the letters remaining white.
- `impl`, `trait`, `type`, `unconstrained`, `distinct`, `pub`, `mut` and `self` are marked as keywords.
- `true` and `false` are now displayed as constants rather than as keywords.
- removed the `Witness` type as it does not exist.

feat: update grammar

---

.vscode/settings.json
package.json
src/EditorLineDecorationManager.ts
src/client.ts
src/extension.ts
src/noir.ts

Adds Command (with codelens `Profile` and key binding `shift+alt+ctrl+n p` to invoke profile command in LSP and display results as line decoration at the end, eg. `// 15 ACIR opcodes`. More detailed information is available on hover of individual code fragment (span).
Part of 
feat: Expose Profile information in vscode https://github.com/noir-lang/noir/issues/3501

feat: add opcodes profile information

---

.eslintignore
.eslintrc.js
.github/workflows/formatting.yml
.prettierrc
package-lock.json
package.json
src/EditorLineDecorationManager.ts
src/client.ts
src/constants.ts
src/extension.ts
src/find-nargo.ts
src/noir.ts

Resolves 
This PR adds the standard linter setup from the Noir monorepo.
As part of this I noticed that we weren't handling brillig opcodes in `EditorLineDecorationManager` which were hidden by not properly typing the functions. This results in no brillig opcodes being reported.

chore: add linter setup

---

.github/workflows/release.yml

Drop's environment reference from release workflow so that approvals through environments are not required.
Resolves:
Align plugin releases procedure to Noir main repo #61

chore: Remove environment reference

---

package.json

https://github.com/noir-lang/vscode-noir/pull/55 added the default configuration:
```json
"editor.formatOnSave":  true
``` 
Useful when users prefer auto-formatting.
Troublesome when users do not, as it overrides VS Code's global `editor.formatOnSave` setting (i.e. users cannot disable auto-formatting on Noir, even when the Format on Save option in VS Code's settings is unchecked).
Remove the override.

chore: Remove format on save override

---

src/client.ts
src/extension.ts
src/find-nargo.ts
src/noir.ts

Partialy resolves 
LSP to set nargo path based on nargo or aztec-nargo [#4233](https://github.com/noir-lang/noir/issues/4233),
Adds
Status Bar item with information about nargo picked.
Indicates with colour and diagnostic message otherwise

feat(aztec): search for aztec-nargo on top of nargo bin

---

package.json
src/client.ts
src/extension.ts

Resolves 
Introduce Code Lens disable setting #63

feat: introduce setting to disable Code Lens feature

---

src/extension.ts

We're currently only updating the tooltip which shows the currently selected binary path when we open a new file. This PR forces this update whenever we update the nargo path.
Resolves

fix: update tooltip when selecting nargo binary

---

src/extension.ts

Start a debug session when the extension receives the `nargo.debug.dap` command
Use the built in `workbench.action.debug.start` vscode command to start the debug session
https://github.com/noir-lang/vscode-noir/assets/13237343/6e83d28c-126a-41ff-a23b-bc7ce9a50ccb
This PR has its sibling in noir repo noir-lang/noir#5474

Start debug session when receiving `nargo.debug.dap` command

---

src/client.ts

The LSP client logs "Starting LSP client using command: ${command} ${args}" on every LSP interaction, not just when the LSP client starts, so that showing out in the output is confusing but also a bit distracting (especially if you are trying to see the actual messages that go between the client and server).
Also, now that we'll show (for now) comptime output in the logs, it's nice if we don't get this extra line for each "compilation".
Removes that log line.
When do we do releases of the extension?

chore: remove debug log

---

src/client.ts
src/debugger.ts
src/extension.ts
src/find-nargo.ts

Asked by Palla, it seems it'll be useful to use in Aztec-Packages.
VSCode doesn't automatically expand variables in settings so some plugins do it. There's no convention about which names to use but at least the cmake plugin uses `workspaceFolder` for the workspace folder, and that's probably the most useful one to have to configure `nargo` relative to it... so that's just what this PR does.
After merging this PR we'd probably need a new release so it can be used.

feat: expand `${workspaceFolder}` in `nargoPath` setting

---

syntaxes/noir.tmLanguage.json

Resolves #89
Resolves #90
A few things here.
Before:
After:
Before:
After:
Before:
After:
Before:
After:

feat: some syntax highlighting improvements

---

src/client.ts

There's debug output that goes into the Noir Language Server output:
When debugging the extension using LSP, or just when trying to look into the output of comptime `println`, that output sometimes gets in the way.
Removes that debug output.
I wanted to get this done before the next release, because it's a minor thing so it can be done quickly.

chore: don't output capabilities to Noir Langauge Server output

---

syntaxes/noir.tmLanguage.json

Resolves #50
A few things here.
Before:
After:
Before:
After:
Before:
After:

feat: better syntax highlighting for strings

---

src/find-nargo.ts

Resolves an issue where if `nargoPath` was empty it wouldn't pick up `nargo` in PATH.
I don't know how it used to work. Maybe by default it starts in `undefined`, but then if you change it and erase it it ends up being an empty string.

fix: find nargo in path if `nargoPath` is blank

---

package.json
src/debugger.ts
src/extension.ts

* trigger dap debugger when receiving `nargo.debug.test` command
* add new `testName` and `oracleResolver` fields to launch configuration
https://github.com/user-attachments/assets/d0186a1a-49e8-44ec-99ce-d57bd633fd64
related to noir-lang/noir#5208

feat(codelens): trigger debugger on 'Debug test' command (#3)

---

package.json
src/extension.ts

No issue, just something nice to have: allow invoking `nargo expand` via LSP.
Goes together with https://github.com/noir-lang/noir/pull/9012
This works similar to Rust Analyzer's "expand macro", except that in our case the entire crate's contents are put in a new document.
Here's it working with a simple file:
Here's with one of Aztec's contracts:
In the future we could add another comment to expand the crate but only show the contents of, for example, the current module. But for now this command alone is good enough because you can make a code change, re-run the command and it'll update the document's content in-place so if you scrolled down to where you had interesting stuff to see you'll see the update you wanted to see.

feat: allow running `nargo expand`
